### ISSUE TITLE
Can you use Environment Variable for API_KEY and API_SECRET?

### ISSUE THREAD

**Issue by glaksmono** [veritrans/veritrans-ruby#23]
https://github.com/veritrans/veritrans-ruby#edit-api-keys-in-configveritransyml

Not a good practice if we have to hardcode this on the .yml file

Can we do the following:

```
staging:
  client_key: <%= ENV['VERITRANS_CLIENT_KEY'] %>
  server_key: <%= ENV['VERITRANS_SERVER_KEY'] %>
  api_host: https://api.sandbox.veritrans.co.id

production:
  client_key: <%= ENV['VERITRANS_CLIENT_KEY'] %>
  server_key: <%= ENV['VERITRANS_SERVER_KEY'] %>
  api_host: https://api.veritrans.co.id
```

Or we need to hard-code it for now?
